apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "relay.fullname" . }}-runtime
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.clusterSecretStore }}
  target:
    name: {{ include "relay.fullname" . }}-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "secrets.relayRuntimeSecretArn is required" .Values.secrets.relayRuntimeSecretArn | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "relay.fullname" . }}-keycloak-runtime
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.clusterSecretStore }}
  target:
    name: {{ include "relay.fullname" . }}-keycloak-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "secrets.keycloakRuntimeSecretArn is required" .Values.secrets.keycloakRuntimeSecretArn | quote }}
