apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relay.fullname" . }}-realm
  labels:
    {{- include "relay.labels" . | nindent 4 }}
data:
  relay-realm.json: |
    {
      "realm": {{ .Values.keycloak.realm | quote }},
      "enabled": true,
      "registrationAllowed": {{ .Values.keycloak.registrationAllowed }},
      "registrationEmailAsUsername": false,
      "loginWithEmailAllowed": true,
      "duplicateEmailsAllowed": false,
      "resetPasswordAllowed": true,
      "verifyEmail": {{ .Values.keycloak.emailVerificationEnabled }},
      "sslRequired": "external",
      "users": [{
        "username": "${RELAY_INITIAL_ADMIN_USERNAME}",
        "email": "${RELAY_INITIAL_ADMIN_EMAIL}",
        "firstName": "Relay",
        "lastName": "Administrator",
        "enabled": true,
        "emailVerified": true,
        "credentials": [{
          "type": "password",
          "value": "${RELAY_INITIAL_ADMIN_PASSWORD}",
          "temporary": true
        }],
        "clientRoles": {
          "realm-management": ["realm-admin"]
        }
      }],
      "clients": [{
        "clientId": "relay",
        "name": "Relay",
        "enabled": true,
        "publicClient": true,
        "standardFlowEnabled": true,
        "directAccessGrantsEnabled": false,
        "serviceAccountsEnabled": false,
        "redirectUris": [
          {{ printf "%s/oauth/callback" .Values.customer.publicOrigin | quote }},
          "relay://oauth/callback"
        ],
        "webOrigins": [{{ .Values.customer.publicOrigin | quote }}],
        "attributes": {
          "pkce.code.challenge.method": "S256",
          "post.logout.redirect.uris": {{ printf "%s/*##relay://oauth/logout" .Values.customer.publicOrigin | quote }}
        },
        "protocolMappers": [{
          "name": "Relay audience",
          "protocol": "openid-connect",
          "protocolMapper": "oidc-audience-mapper",
          "consentRequired": false,
          "config": {
            "included.client.audience": "relay",
            "id.token.claim": "false",
            "access.token.claim": "true"
          }
        }]
      }]
    }
