apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "relay.fullname" . }}-keycloak
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.keycloakMinAvailable }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
{{- if and .Values.autoscaling.enabled .Values.relay.scaleReady }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "relay.fullname" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "relay.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "relay.fullname" . }}-default-deny-ingress
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "relay.fullname" . }}-allow-ingress
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values: [relay]
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - { protocol: TCP, port: 3001 }
        - { protocol: TCP, port: 8080 }
        - { protocol: TCP, port: 9000 }
