apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relay.fullname" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.relay.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "relay.fullname" . }}-keycloak
  labels:
    {{- include "relay.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.keycloak.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
