apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    {{- include "relay.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.service.relayNodePort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "relay.fullname" . }}-keycloak
  labels:
    {{- include "relay.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  sessionAffinity: ClientIP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: {{ .Values.service.keycloakNodePort }}
      protocol: TCP
